name: FinalForgeRestrictor
main: br.com.finalcraft.finalforgerestrictor.FinalForgeRestrictor
version: 2.0.5
author: [EverNife]
depend: [EverNifeCore]
softdepend: [GriefPreventionPlus, GriefPrevention, WorldGuard, PlotSquared, IridiumSkyblock, SuperiorSkyblock2]
api-version: 1.13